tinymce.addI18n('en', {
	"Insert/edit link": "Insert/edit link",
	"tinymce-link-url-page-label": "Link url/page",
	"tinymce-link-display-text-label": "Text to display",
	"tinymce-link-link-trail-label": "Link trail",
	"tinymce-link-link-list-label": "Link list",
	"tinymce-link-target-none": "None",
	"tinymce-link-target-new-window": "New window",
	"tinymce-link-target-label": "Target",
	"tinymce-link-rel-label": "Rel",
	"tinymce-link-type-external": "External",
	"tinymce-link-type-internal": "Internal",
	"tinymce-link-type-label": "Type",
	"tinymce-link-link-list-none": "None",
	"tinymce-link-page-not-found": "(page does not exist)",
	"tinymce-link-want-to-link-email": "The URL you entered seems to be an email address. Do you want to add the required mailto: prefix?",
	"tinymce-link-want-to-link-external": "The URL you entered seems isn't an external link. Do you want to add the required // prefix?",
	"tinymce-link-link-button-tooltip": "Insert/edit link",
	"tinymce-link-link-remove-button-tooltip": "Remove link",
	"tinymce-link-open-link": "Open link",
	"tinymce-link-context-menu": "openlink | link unlink",
	"tinymce-link": "Link",
});